version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Sheridan/nftables_exporter
    docker:
      - image: circleci/golang:1.10.0
    environment:
      - GOCACHE: "/tmp/go/cache"
      - DEP_VERSION: 0.4.1
    steps:
      - checkout
      - run:
          name: build
          command: make build
